name: Build Android

on: 
  - workflow_dispatch: true
  - release:
    types: [published]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11' # only 11 works for this project 

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:

          node-version: 18.x

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26c
          add-to-path: true

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install yarn
        run: npm install -g yarn

      - name: Install App Dependencies
        run: yarn

      - name: Setup App Dependencies
        run: yarn setup

      - name: Configure Platform
        run: yarn clean

      - name: Build Android apk
        run: yarn build android
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      # - name: Build Android prod aab
      #   run: yarn build android
      #   env:
      #     ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      # - name: Sign
      #   run: |
      #         sudo chmod 777 ./utils/scripts/sign.sh
      #         ./utils/scripts/sign.sh

      - name: Upload dev APK
        uses: actions/upload-artifact@v3
        with:
          name: acodenode-debug
          path: ./*.apk

      # - name: Upload release bundle
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: app-release
      #     path: ./*.aab